apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-mfrestorepvc
spec:
  storageClassName: dev-mfrestorestorage
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-nfsrestorestorage
spec:
  storageClassName: dev-mfrestorestorage
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/data/mf/dev_dumps/
    type: DirectoryOrCreate     

---

apiVersion: batch/v1
kind: Job
metadata:
  name: mfrestore
spec:
  template:
    spec:
      containers: 
      - name: mfrestore
        image: 192.168.100.73:31003/repository/mydockerrepo/holgerfischer/myfinance-mfmongobackup:0.17.0-alpha.19
        command: ['sh', '-c',"./restore.sh"]  
        volumeMounts:
         - name: myfinancedumps
           mountPath: /mongodump         
        env: 
        - name: DB_NAME
          value: "product-db"
        - name:  MONGODB_URI
          value: mongodb://192.168.100.73:30029/product-db     
        - name:  MONGODB_USER
          value: root     
        - name:  MONGODB_PASSWORD
          value: vulkan 
        - name:  FILE
          value: product-db-2022-03-25-15:28:04 
      restartPolicy: OnFailure  
      volumes:
      - name: myfinancedumps
        persistentVolumeClaim:
          claimName: dev-mfrestorepvc     
  backoffLimit: 2   