# Default values for mfbackend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 192.168.100.73:31003/repository/mydockerrepo/holgerfischer/myfinance-
  pullPolicy: IfNotPresent

mfdump:
  name: mfdump
  schedule: "1 22 * * 0" 
  dbpw: vulkan

pv:
  pvcname: mfdumppvc
  storage: /mnt/data/mf/prod_dumps/
  storagesize: 5Gi 

